/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChatResponse {
  id?: string;
  isPresentOnline?: boolean;
  lastMessageTime?: string;
  name?: string;
  receiverId?: string;
  senderId?: string;
  unreadCount?: number;
}
